spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application.name: gamestate
  threads.virtual.enabled: true

server:
  forward-headers-strategy: framework
  servlet:
      contextPath: /api

management:
  endpoint.health:
    show-details: "ALWAYS"
  metrics.tags:
    application: ${spring.application.name}
    host: ${spring.application.name}.lostcities.dev
  endpoints:
    web:
      exposure:
        include: "*, openapi, swagger-ui"
      discovery:
        enabled: true
    enabled-by-default: true
  server:
    port: 4452
    base-path: /management/${spring.application.name}
  endpoint:
    env:
      show-values: always

