spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application.name: gamestate

server:
  forward-headers-strategy: framework
  servlet:
      context-path: /api/gamestate

management:
    endpoints:
      web.exposure.include: metrics, prometheus, health
    metrics:
        tags:
            application: ${spring.application.name}

