spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application.name: gamestate

server:
  forward-headers-strategy: framework
  servlet:
      contextPath: /api

management:
  endpoint.health:
    show-details: "ALWAYS"
  metrics.tags:
    application: ${spring.application.name}
    host: ${spring.application.name}.lostcities.dev
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 4452
    base-path: /management/${spring.application.name}

