logging:
  level:
    ROOT: error
    io.dereknelson.lostcities: info
    org.springframework.security.web.FilterChainProxy: debug
    org.hibernate: info
    org.springframework.amqp.rabbit.connection: debug

spring:
  main.allow-circular-references: true
  application.name: gamestate
  profiles:
    active: dev
  rabbitmq:
    host: 172.20.0.60
    port: 5672
    username: guest
    password: guest

  redis:
    database: 0
    host: 172.20.0.61
    port: 6379

server:
  port: 8080
  forward-headers-strategy: framework


management:
    endpoints:
        web.exposure.include: metrics, prometheus
    metrics:
        tags:
            application: ${spring.application.name}

