spring:
  main.allow-circular-references: true
  application.name: gamestate

server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
      context-path: /api/gamestate

management:
    endpoints:
        web.exposure.include: metrics, prometheus
    metrics:
        tags:
            application: ${spring.application.name}

