spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application.name: gamestate

server:
  forward-headers-strategy: framework
  servlet:
      contextPath: /api

management:
    endpoints:
      web.exposure.include: metrics, prometheus, health
    metrics:
        tags:
            application: ${spring.application.name}
    server:
      base-path: /actuator/${spring.application.name}

