spring:
  application.name: gamestate-stage


  rabbitmq:
    addresses: ${sm://lostcities_event_queue_url}
    port: 1883

  redis:
    host:  ${sm://gamestate_store_url}
    port: ${sm://gamestate_store_port}
    password: ${sm://gamestate_store_password}
    database: 0

  cloud:
    consul.enabled: false

logging:
  level:
    ROOT: info
    io.dereknelson.lostcities: info
    org.springframework.security.web.FilterChainProxy: error
    org.springframework.amqp.rabbit.connection: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
    redis.clients.jedis.*: debug
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: '%d{"yyyy-MM-dd''T''HH:mm:ss,SSS"} application=${spring.application.name} profiles=${spring.profiles.active} %-5level [%thread] %logger : %msg%n'
    dateformat: yyyy-MM-dd'T'HH:mm:ssxxx
  file:
    name: /root/Logs/${spring.application.name}-stage.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10

server:
  port: 8092
